### ISSUE TITLE
Error when picking route in `Laravel routes`-picker

### ISSUE THREAD

**Issue by mimre25** [adalessa/laravel.nvim#121]
When I'm using the `Laravel routes` command I get the telescope picker including the "preview" with the route information.
However, upon choosing an entry (hitting enter in my case), I get the following error and remain in the same file as I was before.

```console
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/laravel.nvim/lua/laravel/_lsp/init.lua:19: attempt to call f
ield 'make_config' (a nil value)
stack traceback:
        ...l/share/nvim/lazy/laravel.nvim/lua/laravel/_lsp/init.lua:19: in function 'get_client'
        ...l/share/nvim/lazy/laravel.nvim/lua/laravel/_lsp/init.lua:41: in function 'go_to'
        ...lazy/laravel.nvim/lua/laravel/pickers/common/actions.lua:29: in function 'go'
        ...lazy/laravel.nvim/lua/laravel/pickers/common/actions.lua:40: in function <...lazy/laravel.nvim/lua/laravel/picker
s/common/actions.lua:39>
```

I assume the intended behavior is to navigate to the file the route is defined in.

I'm getting the same error when using `Laravel related`.

**Comment by adalessa** [comment]
@mimre25 The feature to find the class uses the lsp to find it. This is a bit different from PhpActor and Intelephense. Which one are you using ?

**Comment by mimre25** [comment]
I'm using Intelephense these days, as I feel it's working better with laravel than PhpActor.

**Comment by adalessa** [comment]
I will have to find time to check, not using intelephense in a long time. and for me with phpactor still works.

**Comment by mimre25** [comment]
I just tried installing `phpactor` alongside intelephense and then the actions work.

However, `phpactor` doesn't seem to understand laravel/php well enough, I constantly displays errors that things aren't defined and without `intelephense` I couldn't go to definitions and so on.

So unfortunately, using `phpactor` isn't really possible for and I have to uninstall it again.

**Comment by mimre25** [comment]
After doing a little source diving and debugging, I figured out what the problem is:

The default value for `lsp_server` is "phpactor" (see https://github.com/adalessa/laravel.nvim/blob/main/lua/laravel/options/default.lua#L30),

Unfortunately, I can't infer from the docs how I can change this.

That said, I've tried to clone the repo and locally change this default, but then I get another error.
So I guess this needs more work. :/

**Comment by Bleksak** [comment]
You can change lsp_server by changing it in the opts (if you use lazy)
```
opts = {
  lsp_server = "intelephense"
}
```

I can confirm however, that this feature does not properly work when using intelephense.

**Comment by adalessa** [comment]
@Bleksak and @mimre25 I have tested with intelephense and the only time that I got the error is when I have the wrong configuration in the plugin. the plugin has the `lsp_server` which is use to use the different logic on each case.
Can you confirm that you have in your config thee value set ?
```lua
    require('laravel').setup({lsp_server = "intelephense"})
```

**Comment by adalessa** [comment]
I have tested with related and routes and for a general case I see it working as expected.
I think that value could be auto discover, but need some thought on how should work.

**Comment by Bleksak** [comment]
![image](https://github.com/user-attachments/assets/4defae1b-143f-427e-ab2e-9300c9d39853)

On select, I get:

![image](https://github.com/user-attachments/assets/fe2f77a7-d8b5-4c30-aa9f-ff22025be792)

The full error:
```
Error executing vim.schedule lua callback: ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: attempt to call field '_get_symbol_kind_name' (a nil 
value)                                                                                                                                                          
stack traceback:                                                                                                                                                
        ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: in function 'go_to'                                                                     
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:29: in function 'go'                                                                        
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:40: in function <...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:39>            
Error executing vim.schedule lua callback: ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: attempt to call field '_get_symbol_kind_name' (a nil 
value)                                                                                                                                                          
stack traceback:                                                                                                                                                
        ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: in function 'go_to'                                                                     
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:29: in function 'go'                                                                        
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:40: in function <...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:39>            
Error executing vim.schedule lua callback: ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: attempt to call field '_get_symbol_kind_name' (a nil 
value)                                                                                                                                                          
stack traceback:                                                                                                                                                
        ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: in function 'go_to'                                                                     
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:29: in function 'go'                                                                        
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:40: in function <...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:39>            
Error executing vim.schedule lua callback: ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: attempt to call field '_get_symbol_kind_name' (a nil 
value)                                                                                                                                                          
stack traceback:                                                                                                                                                
        ...vim/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:19: in function 'go_to'                                                                     
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:29: in function 'go'                                                                        
        ...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:40: in function <...tart/laravel.nvim/lua/laravel/pickers/common/actions.lua:39>
```


It doesn't work only on some routes. (Looks like nested routes)
Could the issue be, that we're using neovim nightly, where `vim.lsp.util._get_offset_encoding` doesn't exist?

**Comment by adalessa** [comment]
Yeah we should not use the methods starting with underscore.  since they are affected to change.
@Bleksak could you test in that particular case changing the line with 
```
      and vim.lsp.protocol.SymbolKind[location.kind] or '' == "Class"
```
It's the same but not using the function.
For context this is the current logic in this function
```
function M._get_symbol_kind_name(symbol_kind)
  return protocol.SymbolKind[symbol_kind] or 'Unknown'
end
```

**Comment by Bleksak** [comment]
Yes, that fixes the issue.

**Comment by adalessa** [comment]
Thanks, I have pushed the change so it's on main branch

**Comment by adalessa** [comment]
@mimre25 if this solves it for you as well lets close the issue.
Thanks

**Comment by mimre25** [comment]
I can confirm that it works for me when setting 
```
opts = {
  lsp_server = "intelephense"
}
```
in the lazy.lua file.


One interesting aspect that I noticed while testing: The commands assume that the language server is running.
So if I'm in the root directory of a laravel project and just start neovim and then run `Laravel routes`, I still get the picker, but any selection will fail because the language server is not running (it only starts upon entering a php file).
This is not a big deal, IMO.

Anyhow, I think that issue is out of the scope of this issue and you can close it :slightly_smiling_face:
